version: '3'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mhoussem789@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    depends_on:
      - db
  spring:
    build: ./api
    ports:
      - "8083:8083"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  web:
    build: ./web
    ports:
      - "4200:80"
    depends_on:
      - spring